name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Build with dotnet
      run: dotnet build templated.sln --configuration Release
    - name: Tests
      run: dotnet test ./TemplateTests/TemplateTests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover 
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./TemplateTests/coverage.opencover.xml
        name: codecov-umbrella 
