name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '2.2.103', '3.0.100' ]
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with dotnet
      run: |
        export DOTNET_ROOT="$DOTNET_ROOT/${{ matrix.dotnet }}/x64/"
        dotnet restore
        dotnet build templated.sln --configuration Release
        dotnet run -- -h
    - uses: actions/setup-dotnet@v1
    - name: Tests
      run: dotnet test templated.sln --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover 
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./TemplateTests/coverage.opencover.xml
        name: codecov-umbrella 